#!/usr/bin/env python
#
# Copyright (C) 2014 Smithsonian Astrophysical Observatory
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

from __future__ import print_function

toolname = "grow_from_max"
__revision__ = "15 January 2019"


import os
import sys

import ciao_contrib.logger_wrapper as lw
lgr = lw.initialize_logger(toolname)
verb0 = lgr.verbose0
verb1 = lgr.verbose1
verb2 = lgr.verbose2
verb3 = lgr.verbose3
verb5 = lgr.verbose5


def CIAOTemporaryFile( *args, **kwargs ):    
    """
    Force to use ASCDS_WORK_PATH
    """
    from tempfile import NamedTemporaryFile    
    return NamedTemporaryFile(dir=os.environ["ASCDS_WORK_PATH"], *args, **kwargs)


def find_local_max( infile, mask="box(0,0,5,5)"):
    """
    Identify the local peaks in the data.  Value must be the max() valein the
    mask region around the pixel (must be strictly > all surrounding pixels)
    """
    from ciao_contrib.runtool import dmimgfilt
    from ciao_contrib.runtool import dmimgblob

    verb1("Finding local maxima")

    t1 = CIAOTemporaryFile()
    t2 = CIAOTemporaryFile()
    nn = t2.name
    t2.close()
    
    dmimgfilt( infile, t1.name, function="peak", mask=mask, clobber=True)
    dmimgblob( t1.name, nn, thresh=0, src=True, clobber=True )
    return nn


def make_mask( shape, radius ):
    """
    
    """
    
    if "circle" == shape:
        return "circle(0,0,{})".format(radius)
    elif "box" == shape:
        r = float(radius)*2.0
        return "box(0,0,{},{})".format(r,r)
    else:
        raise RuntimeError("Unknown shape '{}'".format(shape))


def _crystal_growth( vv,img ):
    """
    Main loop, removed from below for readability
    """
    ylen = vv.shape[0]
    xlen = vv.shape[1]
    npts = 0

    # make a copy of the current pixel values
    cc = vv.copy()

    # Loop over all pixels
    for yy in range(ylen):
        for xx in range(xlen):            
            # If pixel has already been assigned, then skip it
            if cc[yy,xx] != 0:
                continue

            if not img.valid(xx,yy):
                continue

            # Keep track of how many pixels updated. Stop when npts=0
            npts = npts + 1

            # Initialize output; set to current value
            maxval = cc[yy,xx]

            # Loop +/- 1 in each x and y to look for value > maxval
            # We look in the copy, cc, which is not updated until next
            # interation.
            for dy in [-1,0,1]:
                dyy = yy+dy
                if dyy< 0 or dyy >= ylen:
                    continue
                for dx in [-1,0,1]:
                    dxx = xx+dx
                    if dxx < 0 or dxx >= xlen:
                        continue                    
                    maxval = max( maxval, cc[dyy,dxx] )
            
            # Save the maxval in the output
            vv[yy,xx] = maxval

    return npts
    

def crystal_growth( infile, sitesfile, outfile, clobber ):
    """
    Given a set of local max, grow the regions until they touch and
    cover the image
    """
    from crates_contrib.masked_image_crate import MaskedIMAGECrate

    verb1("Assigning pixels to maxima")

    # Load data
    img = MaskedIMAGECrate(sitesfile,mode="r")
    imgd = img.get_image()
    vv = imgd.values
    n0 = vv.shape[0]*vv.shape[1]

    # Open infile to get subspace
    dss_img = MaskedIMAGECrate(infile,mode="r")
    
    # Loop until all pixel are assigned 
    while True:
        # Stop when all pixels have been assigned.
        npts = _crystal_growth(vv,dss_img)
        verb1("Pixels remaining to be mapped : {}".format( npts ))
        if 0 == npts:
            break

    # Save the values 
    imgd.values = vv    
    img.name = "localmax"
    img.write( outfile, clobber=clobber )


@lw.handle_ciao_errors( toolname, __revision__)
def main():
    """
    
    """
    # get parameters
    from ciao_contrib.param_soaker import get_params
    from ciao_contrib.runtool import dmmaskbin
    from ciao_contrib.runtool import add_tool_history

    # Load parameters
    pars = get_params(toolname, "rw", sys.argv, 
        verbose={"set":lw.set_verbosity, "cmd":verb1} )

    from ciao_contrib._tools.fileio import outfile_clobber_checks
    outfile_clobber_checks(pars["clobber"], pars["outfile"] )
    outfile_clobber_checks(pars["clobber"], pars["binimg"] )

    mask = make_mask( pars["shape"], pars["radius"] )
    
    if (len(pars["sitefile"]) == 0) or ("none" == pars["sitefile"].lower()):
        sitefile = find_local_max( pars["infile"], mask=mask )
    else:
        sitefile = pars["sitefile"]

    crystal_growth( pars["infile"], sitefile, pars["outfile"], pars["clobber"] )
    add_tool_history( pars["outfile"], toolname, pars, toolversion=__revision__)
    
    if len(pars["binimg"])>0 and "none" != pars["binimg"].lower():
        dmmaskbin( pars["infile"], pars["outfile"]+"[opt type=i4]", pars["binimg"], clobber=True)
        add_tool_history( pars["binimg"], toolname, pars, toolversion=__revision__)



if __name__ == "__main__":
    try:
        main()
    except Exception as E:
        print("\n# "+toolname+" ("+__revision__+"): ERROR "+str(E)+"\n", file=sys.stderr)
        sys.exit(1)
    sys.exit(0)



